spring:
  profiles.active: local

---
spring:
  profiles: local
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      autoCommit: false
      driverClassName: org.postgresql.Driver
      jdbcUrl: "jdbc:postgresql://localhost:5432/SupplyChainData"
      username: postgres
      maximumPoolSize: 10
      connectionTimeout: 60000
kafka:
  producer:
    stock:
      bootstrapServers: localhost:9092
      ack: 1
      retriesConfig: 3
      batchSize: 0
      lingerms: 2
      maxInflightConnections: 1
      topic: stock-data-1
      keySerializer: com.apache.kafka.common.serialization.StringSerializer
      valueSerializer: com.apache.kafka.common.serialization.StringSerializer




